import re
from fastapi import APIRouter, Depends, Query, HTTPException
from typing import List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from database import get_db
from models.observation import Observation

from models.camera import Camera
from models.entity import VehicleObservation, PersonObservation

router = APIRouter(prefix="/search", tags=["Search"])

@router.post("")
async def unified_search(
    payload: dict,
    db: AsyncSession = Depends(get_db)
):
    """Unified semantic/attribute search using REAL database records with camera and location details."""
    description = payload.get("description", "").lower()
    
    # Query real observations joined with camera details and resolved entity IDs
    stmt = (
        select(Observation, Camera, VehicleObservation.vehicle_id, PersonObservation.person_id)
        .outerjoin(Camera, Observation.source_camera_id == Camera.cam_id)
        .outerjoin(
            VehicleObservation,
            (Observation.observation_id == VehicleObservation.observation_id) &
            (Observation.timestamp_capture == VehicleObservation.timestamp_capture)
        )
        .outerjoin(
            PersonObservation,
            (Observation.observation_id == PersonObservation.observation_id) &
            (Observation.timestamp_capture == PersonObservation.timestamp_capture)
        )
        .order_by(Observation.timestamp_capture.desc())
        .limit(50)
    )
    result = await db.execute(stmt)
    rows = result.all()
    
    formatted_results = []
    for obs, cam, veh_id, per_id in rows:
        # Extract payload data generated by VideoPipeline
        meta = obs.payload or {}
        color = meta.get("color", "") or ""
        obs_type_str = obs.observation_type.value if hasattr(obs.observation_type, 'value') else str(obs.observation_type)
        veh_type = meta.get("vehicle_class", "Vehicle") if obs_type_str == "VEHICLE" else "Person"
        plate = meta.get("plate", "UNKNOWN")
        desc = f"{color} {veh_type}".strip() if color else veh_type
        
        cam_name = cam.display_name if cam else f"Camera {obs.source_camera_id.split('-')[-1]}"
        location = f"{cam.police_station}, {cam.district}" if (cam and cam.police_station) else (cam.district if cam else "Ahmedabad")
        
        entity_id = veh_id if obs_type_str == "VEHICLE" else per_id

        formatted_results.append({
            "id": entity_id or str(obs.observation_id),
            "entity_id": entity_id,
            "observation_id": str(obs.observation_id),
            "type": obs_type_str,
            "description": desc,
            "plate": plate,
            "camera_id": obs.source_camera_id,
            "camera_name": cam_name,
            "location": location,
            "location_type": cam.location_type if cam else "Highway",
            "timestamp": obs.timestamp_capture.isoformat(),
            "confidence": obs.confidence
        })
    
    # Filter if user provided a search query
    if description:
        search_terms = [t for t in description.lower().split() if t]
        clean_query = re.sub(r"[^a-z0-9]", "", description.lower())
        filtered = []
        for r in formatted_results:
            desc_val = (r["description"] or "").lower()
            plate_val = (r["plate"] or "").lower()
            type_val = (r["type"] or "").lower()
            clean_plate = re.sub(r"[^a-z0-9]", "", plate_val)
            
            searchable_text = f"{desc_val} {plate_val} {type_val}"
            
            # Basic synonym expansion to make search more flexible
            if "sedan" in searchable_text or "vehicle" in searchable_text:
                searchable_text += " car"
            if "two_wheeler" in searchable_text:
                searchable_text += " bike motorcycle scooter"
            if "truck" in searchable_text:
                searchable_text += " lorry heavy"
                
            # Score based on how many search terms match the searchable text
            score = sum(1 for term in search_terms if term in searchable_text)

            # Direct or partial plate match boost (e.g. searching 'GJ-01-AB-1234' matches 'GJ01AB1234')
            if clean_query and clean_plate and clean_plate not in ("unreadable", "unknown"):
                if clean_query == clean_plate:
                    score += 5
                elif clean_query in clean_plate or (len(clean_query) >= 4 and clean_plate in clean_query):
                    score += 3
            
            if score > 0:
                r["_score"] = score
                filtered.append(r)
                
        # Sort results by relevance (highest score first)
        filtered.sort(key=lambda x: x["_score"], reverse=True)
        for r in filtered:
            del r["_score"]
            
        formatted_results = filtered
        
    return {"results": formatted_results}
